<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Stanley.Cli</RootNamespace>
    <AssemblyName>stanley</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stanley.ProjectModel\Stanley.ProjectModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

</Project>
