<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.152.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.152.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="4.152.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.152.1" />
  </ItemGroup>

</Project>
